DELETE http://localhost:3001/api/blogs/5d9c276fe53c0707cc322c09
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcGl0YWFsYXNtYWEiLCJpZCI6IjVkOWM2NDEyZGY2ZTQxMDFkZDFlZGE0MyIsImlhdCI6MTU3MDUzMjMxM30.91zrt1z-T7yA2J2DyU6yk0Q6WXZJY4e35tioBGlhnkA